-- MySQL Script generated by MySQL Workbench
-- Wed Sep 25 14:56:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PLANO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PLANO` (
  `id_plano` INT NOT NULL AUTO_INCREMENT,
  `nome_plano` ENUM('Ouro', 'Prata', 'Bronze', 'Latão') NOT NULL,
  `beneficios` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id_plano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_civil` VARCHAR(255) NOT NULL,
  `sexo` ENUM('Masculino', 'Feminino', 'Outro') NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cidade` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `nome_usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `raio_atuacao` INT NOT NULL,
  `idade_interesse_min` INT NOT NULL,
  `idade_interesse_max` INT NOT NULL,
  `sexo_interesse` ENUM('Masculino', 'Feminino', 'Outro', 'Ambos') NOT NULL,
  `plano_id` INT NOT NULL,
  `descricao_perfil` VARCHAR(2048) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `plano_id _idx` (`plano_id` ASC) VISIBLE,
  CONSTRAINT `plano_id `
    FOREIGN KEY (`plano_id`)
    REFERENCES `mydb`.`PLANO` (`id_plano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FOTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FOTO` (
  `id_foto` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `url_foto` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_foto`),
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CURTIDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CURTIDA` (
  `id_curtida` INT NOT NULL AUTO_INCREMENT,
  `foto_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `data_curtida` DATETIME NOT NULL,
  PRIMARY KEY (`id_curtida`),
  INDEX `foto_id/usuario_id_idx` (`foto_id` ASC) VISIBLE,
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `foto_id`
    FOREIGN KEY (`foto_id`)
    REFERENCES `mydb`.`FOTO` (`id_foto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`INTERESSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INTERESSE` (
  `id_interesse` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_interesse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIO_INTERESSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO_INTERESSE` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `interesse_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `interesse_id`),
  INDEX `interesse_id_idx` (`interesse_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `interesse_id`
    FOREIGN KEY (`interesse_id`)
    REFERENCES `mydb`.`INTERESSE` (`id_interesse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERGUNTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERGUNTA` (
  `id_pergunta` INT NOT NULL AUTO_INCREMENT,
  `texto_pergunta` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_pergunta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RESPOSTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RESPOSTA` (
  `id_resposta` INT NOT NULL AUTO_INCREMENT,
  `pergunta_id` INT NOT NULL,
  `texto_resposta` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_resposta`),
  INDEX `pergunta_id_idx` (`pergunta_id` ASC) VISIBLE,
  CONSTRAINT `pergunta_id`
    FOREIGN KEY (`pergunta_id`)
    REFERENCES `mydb`.`PERGUNTA` (`id_pergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIO_RESPOSTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO_RESPOSTA` (
  `id_usuario_resposta` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `pergunta_id` INT NOT NULL,
  `resposta_id` INT NOT NULL,
  PRIMARY KEY (`id_usuario_resposta`),
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `pergunta_id_idx` (`pergunta_id` ASC) VISIBLE,
  INDEX `resposta_id_idx` (`resposta_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pergunta_id`
    FOREIGN KEY (`pergunta_id`)
    REFERENCES `mydb`.`PERGUNTA` (`id_pergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `resposta_id`
    FOREIGN KEY (`resposta_id`)
    REFERENCES `mydb`.`RESPOSTA` (`id_resposta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LIKE_DISLIKE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LIKE_DISLIKE` (
  `id_like_dislike` INT NOT NULL AUTO_INCREMENT,
  `usuario_doador_id` INT NOT NULL,
  `usuario_receptor_id` INT NOT NULL,
  `tipo` ENUM('like', 'dislike') NOT NULL,
  `data_hora` DATETIME NOT NULL,
  PRIMARY KEY (`id_like_dislike`),
  INDEX `usuario_doador/receptor_idx` (`usuario_doador_id` ASC, `usuario_receptor_id` ASC) VISIBLE,
  CONSTRAINT `usuario_doador/receptor`
    FOREIGN KEY (`usuario_doador_id` , `usuario_receptor_id`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario` , `id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MSG_PRIVADA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MSG_PRIVADA` (
  `id_mensagem` INT NOT NULL AUTO_INCREMENT,
  `conteudo` TEXT NOT NULL,
  `usuario_envia_id` INT NOT NULL,
  `usuario_recebe_id` INT NOT NULL,
  `conteudo` VARCHAR(255) NOT NULL,
  `data_envio` DATETIME NOT NULL,
  `data_leitura` DATETIME NULL,
  PRIMARY KEY (`id_mensagem`),
  INDEX `usuario_envia_id_idx` (`usuario_envia_id` ASC, `usuario_recebe_id` ASC) VISIBLE,
  CONSTRAINT `usuario_envia_id/usuario_recebe_id`
    FOREIGN KEY (`usuario_envia_id` , `usuario_recebe_id`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario` , `id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MATCH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MATCH` (
  `id_match` INT NOT NULL AUTO_INCREMENT,
  `usuario_1_id` INT NOT NULL,
  `usuario_2_id` INT NOT NULL,
  `data_sugestao` DATETIME NOT NULL,
  PRIMARY KEY (`id_match`),
  INDEX `usuario_1/2_idx` (`usuario_1_id` ASC, `usuario_2_id` ASC) VISIBLE,
  CONSTRAINT `usuario_1/2`
    FOREIGN KEY (`usuario_1_id` , `usuario_2_id`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario` , `id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GRUPO_RELACIONAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GRUPO_RELACIONAMENTO` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `nome_grupo` VARCHAR(255) NOT NULL,
  `usuario_admin_id` INT NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  PRIMARY KEY (`id_grupo`),
  INDEX `usuario_admin_id _idx` (`usuario_admin_id` ASC) VISIBLE,
  CONSTRAINT `usuario_admin_id `
    FOREIGN KEY (`usuario_admin_id`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GRUPO_PARTICIPANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GRUPO_PARTICIPANTE` (
  `grupo_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`grupo_id`, `usuario_id`),
  INDEX `usuario_id _idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `grupo_id `
    FOREIGN KEY (`grupo_id`)
    REFERENCES `mydb`.`GRUPO_RELACIONAMENTO` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_id `
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GRUPO_MENSAGEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GRUPO_MENSAGEM` (
  `id_mensagem` INT NOT NULL AUTO_INCREMENT,
  `grupo_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `conteudo` TEXT NOT NULL,
  `data_envio` DATETIME NOT NULL,
  `tipo_mensagem` ENUM('texto', 'foto', 'audio') NOT NULL,
  PRIMARY KEY (`id_mensagem`),
  INDEX `grupo_id _idx` (`grupo_id` ASC) VISIBLE,
  INDEX `usuario_id _idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `grupo_id `
    FOREIGN KEY (`grupo_id`)
    REFERENCES `mydb`.`GRUPO_RELACIONAMENTO` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_id `
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BLOCK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BLOCK` (
  `id_bloqueio` INT NOT NULL AUTO_INCREMENT,
  `usuario_bloqueador_id` INT NOT NULL,
  `usuario_bloqueado_id` INT NOT NULL,
  `data_bloqueio` DATETIME NOT NULL,
  PRIMARY KEY (`id_bloqueio`),
  INDEX `BLOCK_idx` (`usuario_bloqueador_id` ASC, `usuario_bloqueado_id` ASC) VISIBLE,
  CONSTRAINT `BLOCK`
    FOREIGN KEY (`usuario_bloqueador_id` , `usuario_bloqueado_id`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario` , `id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
